<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Earls-MacBook-Pro.local" name="FirstTest" tests="2" failures="1" timestamp="30 Oct 2015 16:38:04 GMT" time="65.748" errors="0">
  <testcase name="login" time="43.954" classname="LearningTestNG.TestNGAnotation_1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at LearningTestNG.TestNGAnotation_1.login(TestNGAnotation_1.java:95)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="logout" time="0.0" classname="LearningTestNG.TestNGAnotation_1">
    <skipped/>
  </testcase> <!-- logout -->
</testsuite> <!-- FirstTest -->
